package schemas

// Code generated by genserver.go. DO NOT EDIT.

import (
	"time"
)

type Comment struct {
	ID      string `json:"id"`
	Comment string `json:"comment"`
	Creator string `json:"creator"`
	Public  bool   `json:"public"`
}

type CommentDetail struct {
	ID        string    `json:"id"`
	Comment   string    `json:"comment"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Creator   string    `json:"creator"`
	Updater   string    `json:"updater"`
	Public    bool      `json:"public"`
}

type Template struct {
	ID   string   `json:"id"`
	Body string   `json:"body"`
	Vars []string `json:"vars"`
}

type Information struct {
	Begin  time.Time `json:"begin"`
	End    time.Time `json:"end"`
	Detail string    `json:"detail"`
	ID     string    `json:"id"`
	Type   string    `json:"type"`
}

type InformationDetail struct {
	Type       string    `json:"type"`
	Begin      time.Time `json:"begin"`
	TemplateID string    `json:"template_id"`
	CreatedAt  time.Time `json:"created_at"`
	Updater    string    `json:"updater"`
	Comments   []string  `json:"comments"`
	ID         string    `json:"id"`
	Detail     string    `json:"detail"`
	UpdatedAt  time.Time `json:"updated_at"`
	Creator    string    `json:"creator"`
	End        time.Time `json:"end"`
}
