package faultinfo

// Code generated by genserver.go. DO NOT EDIT.

func GetInformationTemplateIDList() ([]string, error) {
}

func CreateInformationTemplate() error {
}

func GetInformationTemplateDetail(id string) (schemas.Template, error) {
}

func DeleteInformationTemplate(id string) error {
}

func GetInformationList() ([]schemas.Information, error) {
}

func CreateInformation() (responses.InformationCreated, error) {
}

func GetInformationDetail(id string) (schemas.InformationDetail, error) {
}

func UpdateInformation(id string) error {
}

func DeleteInformation(id string) error {
}

func GetCommentList(id string) ([]schemas.Comment, error) {
}

func CreateComment(id string) (responses.CommentCreated, error) {
}

func GetCommentDetail(infoId string, commentId string) (schemas.CommentDetail, error) {
}

func UpdateComment(infoId string, commentId string) error {
}

func DeleteComment(infoId string, commentId string) error {
}

func GetInformationTypelist() ([]string, error) {
}

func CreateInformationType() error {
}

func DeleteInformationType(typ string) error {
}
