package input

// Code generated by genserver.go. DO NOT EDIT.

type CreateInformation struct {
	Vars       map[string]string
	Type       string
	TemplateID string
}

type CreateInfoType string

type DeleteInfoType string

type CreateComment struct {
	Comment string
}

type CreateTemplate struct {
	ID       string
	Template string
}

type UpdateTemplate struct {
	Template string
}
