package schema

// Code generated by genserver.go. DO NOT EDIT.

type Information struct {
	End    time.Time `json:"end"`
	Detail string    `json:"detail"`
	ID     string    `json:"id"`
	Type   string    `json:"type"`
	Begin  time.Time `json:"begin"`
}

type InformationDetail struct {
	Creator    string    `json:"creator"`
	Comments   []string  `json:"comments"`
	Type       string    `json:"type"`
	End        time.Time `json:"end"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
	Updater    string    `json:"updater"`
	ID         string    `json:"id"`
	Begin      time.Time `json:"begin"`
	Detail     string    `json:"detail"`
	TemplateID string    `json:"template_id"`
}

type Comment struct {
	ID      string  `json:"id"`
	Comment string  `json:"comment"`
	Creator string  `json:"creator"`
	Public  boolean `json:"public"`
}

type CommentDetail struct {
	Public    boolean   `json:"public"`
	ID        string    `json:"id"`
	Comment   string    `json:"comment"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Creator   string    `json:"creator"`
	Updater   string    `json:"updater"`
}

type Template struct {
	ID   string   `json:"id"`
	Body string   `json:"body"`
	Vars []string `json:"vars"`
}
